name: Build pkgsrc Libero GNU/Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        category:
          - archivers
          - audio
          - benchmarks
          - cad
          - chat
          - converters
          - databases
          - devel
          - editors
          - emulators
          - fonts
          - games
          - geography
          - graphics
          - ham
          - lang
          - mail
          - math
          - misc
          - multimedia
          - net
          - news
          - pkgtools
          - print
          - security
          - shells
          - sysutils
          - textproc
          - time
          - www
          - x11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build category in pure i386 Debian
        run: |
          docker run --rm -t \
            -v $GITHUB_WORKSPACE:/workspace \
            -w /workspace \
            i386/debian:bookworm bash -c "
            set -e

            # Install build essentials
            apt-get update
            apt-get install -y build-essential make bmake git wget tar bash ccache rsync pkg-config ca-certificates sudo

            # Download and extract pkgsrc
            wget https://cdn.netbsd.org/pub/pkgsrc/pkgsrc-2025Q3/pkgsrc-2025Q3.tar.gz
            tar -xzf pkgsrc-2025Q3.tar.gz

            # Bootstrap pkgsrc into /usr/pkg
            cd pkgsrc/bootstrap
            ./bootstrap --abi 32 --prefer-pkgsrc yes --compiler gcc --prefix=/usr/pkg

            # Configure environment
            echo '/usr/pkg/bin' >> /etc/profile
            export PATH=/usr/pkg/bin:\$PATH

            MKCONF=/usr/pkg/etc/mk.conf
            sudo mkdir -p "$(dirname "$MKCONF")"
            sudo echo "PKGSRC_COMPILER= gcc" >> "$MKCONF"
            sudo echo "CFLAGS+=      \"-march=i586 -mtune=i586\"" >> "$MKCONF"
            sudo echo "CXXFLAGS+=    \"-march=i586 -mtune=i586\"" >> "$MKCONF"
            sudo echo "LDFLAGS+=     \"-march=i586 -mtune=i586\"" >> "$MKCONF"
            sudo echo "ABI=32" >> "$MKCONF"
            sudo echo "MACHINE_ARCH= i386" >> "$MKCONF"
            echo "PREFER_PKGSRC= yes" >> "$MKCONF"

            # Install pbulk
            cd /workspace/pkgsrc/pkgtools/pbulk
            sudo /usr/pkg/bin/bmake install

            # Configure pbulk
            mkdir -p ~/.pbulk
            echo "CHROOT=" > ~/.pbulk/pbulk.conf
            echo "BASEDIR=/usr/pkg" >> ~/.pbulk/pbulk.conf
            echo "PKG_PATH=/usr/pkg/packages" >> ~/.pbulk/pbulk.conf
            echo "JOBS=$(nproc)" >> ~/.pbulk/pbulk.conf
            echo "KEEP_GOING=yes" >> ~/.pbulk/pbulk.conf
            echo "LOGFILE=/tmp/pbulk.log" >> ~/.pbulk/pbulk.conf


            # Build selected category
            cd /workspace/pkgsrc
            sudo /usr/pkg/bin/pbulk -c ~/.pbulk/pbulk.conf -C /workspace/pkgsrc/${{ matrix.category }}

            # Collect built packages
            mkdir -p /workspace/tmp/artifacts/${{ matrix.category }}
            rsync -av /usr/pkg/packages/${{ matrix.category }}/ /workspace/tmp/artifacts/${{ matrix.category }}/ || true
            du -sh /workspace/tmp/artifacts/${{ matrix.category }}
            "

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pkgsrc-${{ matrix.category }}
          path: tmp/artifacts/${{ matrix.category }}
