name: pkgsrc Libero GNU/Linux

on:
  workflow_dispatch:

jobs:
  build:
    name: Build pkgsrc (${{ matrix.category }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        category:
          - archivers
          - audio
          - benchmarks
          - cad
          - chat
          - converters
          - databases
          - devel
          - editors
          - emulators
          - fonts
          - games
          - geography
          - graphics
          - ham
          - lang
          - mail
          - math
          - misc
          - multimedia
          - net
          - news
          - pkgtools
          - print
          - security
          - shells
          - sysutils
          - textproc
          - time
          - www
          - x11

    container:
      image: i386/debian:bookworm
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build essentials and pkgsrc dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            make \
            bmake \
            git \
            curl \
            pkg-config \
            ca-certificates \
            wget \
            tar \
            bash \
            ccache \
            rsync

      - name: Download pkgsrc 2025Q3
        run: |
          wget https://cdn.netbsd.org/pub/pkgsrc/pkgsrc-2025Q3/pkgsrc-2025Q3.tar.gz
          tar -xzf pkgsrc-2025Q3.tar.gz

      - name: Bootstrap pkgsrc into /usr/pkg
        run: |
          cd pkgsrc/bootstrap
          ./bootstrap --abi 32 --prefer-pkgsrc yes --compiler gcc --prefix=/usr/pkg
          echo "/usr/pkg/bin" >> $GITHUB_PATH

      - name: Configure mk.conf for multilib and tuning
        run: |
          MKCONF="/usr/pkg/etc/mk.conf"
          mkdir -p "$(dirname "$MKCONF")"
          tee -a "$MKCONF" << 'EOF'
          # Use gcc as compiler
          PKGSRC_COMPILER= gcc

          # Add multilib / 32-bit-specific flags
          CFLAGS+=      "-march=i586 -mtune=i586"
          CXXFLAGS+=    "-march=i586 -mtune=i586"
          LDFLAGS+=     "-march=i586 -mtune=i586"

          # Force ABI and machine arch
          ABI=32
          MACHINE_ARCH= i386

          # Prefer pkgsrc-built tools
          PREFER_PKGSRC= yes

          EOF

      - name: Install pbulk
        run: |
          cd pkgsrc/pkgtools/pbulk
          /usr/pkg/bin/bmake install

      - name: Configure pbulk
        run: |
          mkdir -p ~/.pbulk
          cat > ~/.pbulk/pbulk.conf << 'EOF'
          CHROOT=
          BASEDIR=/usr/pkg
          PKG_PATH=/usr/pkg/packages
          JOBS=$(nproc)
          KEEP_GOING=yes
          LOGFILE=/tmp/pbulk.log
          EOF

      - name: Build category with pbulk
        run: |
          cd pkgsrc
          /usr/pkg/bin/pbulk -c ~/.pbulk/pbulk.conf -C $GITHUB_WORKSPACE/pkgsrc/${{ matrix.category }}

      - name: Collect built packages
        run: |
          mkdir -p /tmp/artifacts/${{ matrix.category }}
          rsync -av /usr/pkg/packages/${{ matrix.category }}/ /tmp/artifacts/${{ matrix.category }}/ || true
          du -sh /tmp/artifacts/${{ matrix.category }}

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pkgsrc-${{ matrix.category }}
          path: /tmp/artifacts/${{ matrix.category }}
