name: pkgsrc Libero GNU/Linux

on:
  workflow_dispatch:

jobs:
  build:
    name: Build pkgsrc (${{ matrix.category }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        category:
          - archivers
          - audio
          - benchmarks
          - cad
          - chat
          - converters
          - databases
          - devel
          - editors
          - emulators
          - fonts
          - games
          - geography
          - graphics
          - ham
          - lang
          - mail
          - math
          - misc
          - multimedia
          - net
          - news
          - pkgtools
          - print
          - security
          - shells
          - sysutils
          - textproc
          - time
          - www
          - x11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build essentials and multilib for i386
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-multilib \
            g++-multilib \
            make \
            bmake \
            git \
            curl \
            pkg-config \
            libssl-dev:i386 \
            zlib1g-dev:i386 \
            libbz2-dev:i386 \
            libc6-dev-i386 \
            ca-certificates \
            wget \
            tar \
            bash \
            ccache \
            rsync \
            nodejs \
            npm

      - name: Download pkgsrc 2025Q3
        run: |
          wget https://cdn.netbsd.org/pub/pkgsrc/pkgsrc-2025Q3/pkgsrc-2025Q3.tar.gz
          tar -xzf pkgsrc-2025Q3.tar.gz

      - name: Bootstrap pkgsrc into /usr/pkg
        run: |
          cd pkgsrc/bootstrap
          sudo ./bootstrap --abi 32 --machine-arch=i386 --prefer-pkgsrc --compiler=gcc --prefix=/usr/pkg
          echo "/usr/pkg/bin" >> $GITHUB_PATH

      - name: Set target architecture
        run: |
          export PKG_DEFAULT_MACHINE=i386
          export PKG_DEFAULT_ABI=linux
          echo "PKG_DEFAULT_MACHINE=$PKG_DEFAULT_MACHINE" >> $GITHUB_ENV
          echo "PKG_DEFAULT_ABI=$PKG_DEFAULT_ABI" >> $GITHUB_ENV

      - name: Install pbulk
        run: |
          cd pkgsrc/pkgtools/pbulk
          sudo /usr/pkg/bin/bmake install

      - name: Configure pbulk
        run: |
          mkdir -p ~/.pbulk
          cat > ~/.pbulk/pbulk.conf << 'EOF'
          CHROOT=
          BASEDIR=/usr/pkg
          PKG_PATH=/usr/pkg/packages
          JOBS=$(nproc)
          KEEP_GOING=yes
          LOGFILE=/tmp/pbulk.log
          EOF

      - name: Build category with pbulk
        run: |
          cd pkgsrc
          sudo /usr/pkg/bin/pbulk -c ~/.pbulk/pbulk.conf -C $GITHUB_WORKSPACE/pkgsrc/${{ matrix.category }}

      - name: Collect built packages
        run: |
          mkdir -p /tmp/artifacts/${{ matrix.category }}
          rsync -av /usr/pkg/packages/${{ matrix.category }}/ /tmp/artifacts/${{ matrix.category }}/ || true
          du -sh /tmp/artifacts/${{ matrix.category }}

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pkgsrc-${{ matrix.category }}
          path: /tmp/artifacts/${{ matrix.category }}
