name: Build pkgsrc Libero GNU/Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        category:
          - archivers
          - audio
          - benchmarks
          - cad
          - chat
          - converters
          - databases
          - devel
          - editors
          - emulators
          - fonts
          - games
          - geography
          - graphics
          - ham
          - lang
          - mail
          - math
          - misc
          - multimedia
          - net
          - news
          - pkgtools
          - print
          - security
          - shells
          - sysutils
          - textproc
          - time
          - www
          - x11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build category in pure i386 Debian
        run: |
          docker run --rm -t \
            -v $GITHUB_WORKSPACE:/workspace \
            -w /workspace \
            i386/debian:bookworm bash -c "
              set -e
              
              # Install build essentials
              apt-get update
              apt-get install -y build-essential make bmake git wget tar bash ccache rsync pkg-config ca-certificates

              # Download and extract pkgsrc
              wget https://cdn.netbsd.org/pub/pkgsrc/pkgsrc-2025Q3/pkgsrc-2025Q3.tar.gz
              tar -xzf pkgsrc-2025Q3.tar.gz

              # Bootstrap pkgsrc into /usr/pkg
              cd pkgsrc/bootstrap
              ./bootstrap --abi 32 --prefer-pkgsrc yes --compiler gcc --prefix=/usr/pkg

              # Configure environment
              echo '/usr/pkg/bin' >> /etc/profile
              export PATH=/usr/pkg/bin:$PATH

              # Configure mk.conf for multilib and tuning
              MKCONF=/usr/pkg/etc/mk.conf
              mkdir -p \"\$(dirname \"$MKCONF\")\"
              tee -a \"$MKCONF\" << 'EOF'
              PKGSRC_COMPILER= gcc
              CFLAGS+=      \"-march=i586 -mtune=i586\"
              CXXFLAGS+=    \"-march=i586 -mtune=i586\"
              LDFLAGS+=     \"-march=i586 -mtune=i586\"
              ABI=32
              MACHINE_ARCH= i386
              PREFER_PKGSRC= yes
              EOF

              # Install pbulk
              cd /workspace/pkgsrc/pkgtools/pbulk
              /usr/pkg/bin/bmake install

              # Configure pbulk
              mkdir -p ~/.pbulk
              cat > ~/.pbulk/pbulk.conf << 'EOF'
              CHROOT=
              BASEDIR=/usr/pkg
              PKG_PATH=/usr/pkg/packages
              JOBS=\$(nproc)
              KEEP_GOING=yes
              LOGFILE=/tmp/pbulk.log
              EOF

              # Build selected category
              cd /workspace/pkgsrc
              /usr/pkg/bin/pbulk -c ~/.pbulk/pbulk.conf -C /workspace/pkgsrc/${{ matrix.category }}

              # Collect built packages
              mkdir -p /workspace/tmp/artifacts/${{ matrix.category }}
              rsync -av /usr/pkg/packages/${{ matrix.category }}/ /workspace/tmp/artifacts/${{ matrix.category }}/ || true
              du -sh /workspace/tmp/artifacts/${{ matrix.category }}
            "

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pkgsrc-${{ matrix.category }}
          path: tmp/artifacts/${{ matrix.category }}
